### ISSUE TITLE
Error after Python update?

### ISSUE THREAD

**Issue by mattdarragh** [cowboysdude/Pir-Sensor#1]
My PIR process has started hanging following a Python update on my RPI3b, I suspect. The issue reappears after restarting, and I can't quite figure out what causes the initial error.

I run the pir process via PM2, which logged the following:

```
Traceback (most recent call last):
  File "/home/pi/pir.py", line 6, in <module>
    import subprocess
  File "/usr/lib/python2.7/subprocess.py", line 430, in <module>
    import pickle
  File "/usr/lib/python2.7/pickle.py", line 171, in <module>
    class Pickler:
  File "/usr/lib/python2.7/pickle.py", line 728, in Pickler
    dispatch[InstanceType] = save_inst
KeyboardInterrupt
```

I'm running GPIO v 2.44 and everything else on my Pi appears to be updated and in order. I know this is likely a simple issue, but I'm not a Python guy. 

My lightly edited version of the pir.py code follows.

```
#!/usr/bin/env python
 
import sys
import time
import RPi.GPIO as io
import subprocess
 
io.setmode(io.BCM)
SHUTOFF_DELAY = 300  # seconds
PIR_PIN = 14        # Pin 8 on the board
 
def main():
    io.setup(PIR_PIN, io.IN)
    turned_off = False
    last_motion_time = time.time()
 
    while True:
        if io.input(PIR_PIN):
            last_motion_time = time.time()
            sys.stdout.flush()
            if turned_off:
                turned_off = False
                turn_on()
        else:
            if not turned_off and time.time() > (last_motion_time + SHUTOFF_DELAY):
                turned_off = True
                turn_off()
        time.sleep(5)
 
def turn_on():
    subprocess.call("sh monitor_on.sh", shell=True)

def turn_off():
    subprocess.call("sh monitor_off.sh", shell=True)

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        io.cleanup()
```

**Comment by cowboysdude** [comment]
Sorry I haven't been paying very good attention!!!  Thank you for the fix!!!!!!!
